variables:
  workspace: linphone.xcworkspace
  scheme: linphone
  destination: name=iPhone 13 Pro
  testResult_path: derivedData/Logs/Test
  
stages:
  - Build
  - UITests

before_script:
  - pod install
  - pwd
  - sed 's/fileprivate let tableView =/public let tableView =/g' ./Pods/DropDown/DropDown/src/DropDown.swift > tmp.swift && mv -f tmp.swift ./Pods/DropDown/DropDown/src/DropDown.swift

Compile & Build:
  stage: Build
  tags: ["macmini-m1-xcode13"]
  before_script:
    - pod install --repo-update
    - pwd
    - sed 's/fileprivate let tableView =/public let tableView =/g' ./Pods/DropDown/DropDown/src/DropDown.swift > tmp.swift && mv -f tmp.swift ./Pods/DropDown/DropDown/src/DropDown.swift
    - xcrun simctl shutdown "$destination" && xcrun simctl erase "$destination"
  script:
    - xcodebuild -workspace $workspace -scheme $scheme -UseModernBuildSystem=YES -destination "$destination" -derivedDataPath derivedData
  after_script: []

  artifacts:
    paths:
      - derivedData/Build
    when: always
    expire_in: 2 hour



after_script:
  - ${TRAINER_EXE} -p $testResult_path/*.xcresult -o $testResult_path/
  - ${XCPARSE_EXE} attachments $testResult_path/*.xcresult results --uti public.image
  - mv $testResult_path/*.xcresult results && mv derivedData/logs.txt results

Call Views:
  stage: UITests
  tags: ["macmini-m1-xcode13"]
  dependencies: ["Compile & Build"]
  script:
    - xcodebuild test -workspace $workspace -scheme $scheme -sdk iphonesimulator -destination "$destination" -UseModernBuildSystem=YES -testPlan Default -derivedDataPath derivedData | tee derivedData/logs.txt

  artifacts:
    paths:
      - results/*
    when: always
    reports:
      junit:
        - $testResult_path/*.xml
    expire_in: 4 week
