# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Push a new beta build to TestFlight"

    lane :tests do
        run_tests(
            code_coverage: true,
            devices: ["iPhone 6s", "iPad Air"], # TODO: Add more devices
            scheme: "linphone",
            workspace: "linphone.xcworkspace"
            )
    end

    lane :beta do
        get_certificates           # invokes cert
        get_provisioning_profile   # invokes sigh
        increment_build_number(xcodeproj: "linphone.xcodeproj")
        build_app( 
            scheme: "linphone",
            silent: true,
            workspace: "linphone.xcworkspace")
        notification(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Building",
            message: "Ready to upload...")
        upload_to_testflight
        notification(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Uploading",
            message: "In a few minutes, you'll be able to test your application.")
    end

    lane :release do
        capture_screenshots
        frame_screenshots(white: true)
        notification(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Screenshotting", 
            message: "In a few minutes, you'll be able to release your application.")
        build_app
        upload_to_app_store
        notification(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Uploading", 
            message: "In a few minutes, you'll be able to release your application.")
    end
end

platform :android do
    desc "Push a new Beta build to Play Store Console"

    lane :tests do
        # TODO: Replace test with the gradle task name for running unit tests of your app.
        gradle(task: "test")
        notification(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished testing", 
            message: "You can continue the development")
    end
end

lane :notif do
    desc "Test notif"

    notification(
        app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
        content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
        subtitle: "Finished Building", 
        message: "Ready to upload...")
end

lane :voipiu do

    lane :beta do
        get_certificates           # invokes cert
        get_provisioning_profile   # invokes sigh
        increment_build_number(xcodeproj: "linphone.xcodeproj")
        build_app( 
            scheme: "linphone",
            silent: true,
            workspace: "linphone.xcworkspace")
        notification(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Building", 
            message: "Ready to upload...")
        upload_to_testflight
        notification(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Uploading", 
            message: "In a few minutes, you'll be able to test your application.")
    end
end