# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Always mantains platforms specific lanes consistant.
default_platform(:ios)

# Bump version lanes and similar doesn't belong to a platform.

desc "All ios specific lanes"
platform :ios do

    desc "Prepare local environment for development."
    desc "Install development certificates and provisioning profiles."
    desc "Add new devices to devices.txt list if you need them for testing."
    desc "If you don't have development certificates yet set `readonly` options to `false`. Do this only if you know what are you doing, since this lane invalidate and create certificates again."
    desc "After this action has finished, the obtained certificates and provisioning profile have to be manually linked to the project from linphone project windown inside xCode."
    lane :prepare_development do
        bundle_identifier = ENV["BUNDLE_IDENTIFIER"]
        register_devices(devices_file: "./fastlane/devices.txt")
        # Generate development certs and profiles.
        match(
            type: "development",
            force_for_new_devices: true,
            readonly: true,
        )
    end

    desc "Execute automatic tests and produce a code coverage report."
    desc "Be sure to have installed on your machine all devices defined in *devices array*."
    lane :tests do
        run_tests(
            code_coverage: true,
            devices: ["iPhone 12 Pro Max"], # TODO: Add more devices, like "iPhone SE (1st generation) (14.5)"
            scheme: "linphone",
            workspace: "linphone.xcworkspace"
            )
    end

    desc "Prepare the build number for the next build to deploy."
    lane :prepare_version do
        ENV["tf_build"] = prepare_version_and_build
    end

    desc "Push a new beta build to TestFlight."
    lane :beta do
        # get_certificates           # invokes cert
        # get_provisioning_profile   # invokes sigh
        prepare_version
        beta_rebranding
    end

    desc "Push a new beta build to Testflight without incrementing the build number."
    desc "Only use to publish apps for rebranding, after having incremented the main build number."
    desc "If you push without incrementing build number, it will be rejected."
    desc "If is the first time of match certifications before submitting a version to Testflight, you have to generate new match certificates manually with the command `bundle exec fastlane run match type:appstore --env appstore`."
    desc "If reports doesn't contains bytecode and crash reports but only feedback.json file, it maybe possible that you have missed to upload symbols to crashlytics."
    lane :beta_rebranding do
        match(type:"appstore", readonly: true)
        build_app(
            include_bitcode: true,
            include_symbols: true,
            scheme: "linphone",
            silent: true,
            workspace: "linphone.xcworkspace"
            )

        notif(message: "Ready to upload...", subtitle: "Finished Building")

        upload_to_testflight(
            skip_waiting_for_build_processing: is_ci
        )
        upload_symbols_to_crashlytics(dsym_path: "../#{ENV["PRODUCT_NAME"]}.app.dSYM.zip")
        
        notif(message: "In a few minutes, you'll be able to test your application.", subtitle: "Finished Uploading")

        after_deployment
    end

    lane :release do
        capture_screenshots
        frame_screenshots(white: true)
        
        notif(message: "In a few minutes, you'll be able to release your application.", subtitle: "Finished Screenshotting")

        build_app
        upload_to_app_store

        notif(message: "In a few minutes, you'll be able to release your application.", subtitle: "Finished Uploading")
    end

    # This lane is called, only if the executed lane was successful
    lane :after_deployment do # |lane|
        clean_ipa
        commit_version
        # notif "Fastlane finished '#{lane}' successfully" # Mac OS X Notification
    end
    
    desc "Clean all useless .ipa files."
    lane :clean_ipa do
        File.delete("../#{ENV["PRODUCT_NAME"]}.ipa")
        File.delete("../#{ENV["PRODUCT_NAME"]}.app.dSYM.zip")
    end
    
    lane :commit_version do
        commit_message = "Version bump to #{ENV["tf_build"]} made by Fastlane."
        commit_version_bump(
            force: true,
            message: commit_message,
            xcodeproj: "linphone.xcodeproj" # optional, if you have multiple Xcode project files, you must specify your main project here
        )
    end

    error do |ex|
        notif "Error in Fastlane. Check the console output."
    end
end

desc "All Android specific lanes"
platform :android do

    desc "Run unit tests for gradle builds"
    lane :tests do
        # TODO: Replace test with the gradle task name for running unit tests of your app.
        gradle(task: "test")
        
        notif(message: "You can continue the development", subtitle: "Finished testing")
    end
end

desc "Test notif"
lane :notif do |options|
    app_icon = options[:app_icon] || "./Resources/images.xcassets/AppIcon.appiconset/1024.png"
    content_image = options[:content_image] || "./Resources/images.xcassets/AppIcon.appiconset/1024.png"
    message = options[:message] || "Your notification is shown and notify you about a new event happened in your system, generated by a lane executed by you or a script. You can interact with that if you want or ignore it. This text has to be long to test how many chars a notification message can show at the same time."
    title = options[:title] || "Fastlane Notification"

    notification(
        app_icon: app_icon,
        content_image: content_image,
        message: message,
        subtitle: options[:subtitle], 
        title: title)
end

lane :voipiu do
    lane :beta do
        get_certificates           # invokes cert
        get_provisioning_profile   # invokes sigh
        increment_build_number(xcodeproj: "linphone.xcodeproj")
        build_app( 
            scheme: "linphone",
            silent: true,
            workspace: "linphone.xcworkspace")
        notif(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Building", 
            message: "Ready to upload...")
        upload_to_testflight
        notif(
            app_icon: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            content_image: "./Resources/images.xcassets/AppIcon.appiconset/1024.png",
            subtitle: "Finished Uploading", 
            message: "In a few minutes, you'll be able to test your application.")
    end
end
