# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
    ENV["MATTERMOST_WEBHOOK_URL"] = 'https://my_new_webooh_from_mattermost'
end

def send_message_to_mattermost(options)
    unless ENV['MATTERMOST_WEBHOOK_URL'].nil? || ENV['MATTERMOST_WEBHOOK_URL'].empty?
        mattermost(
            pretext: options[:pretext],
            message: options[:msg],
            default_payloads: options[:default_payloads],
            username: 'Fastlane',
            icon_url: 'https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png',
            payload: {},
            attachment_properties: {
                title: options[:title],
                thumb_url: options[:thumb_url],
                fields: [{
                     title: 'Version',
                     value: options[:version_number],
                     short: true
                },
                {
                     title: 'Build Number',
                     value: options[:build_number],
                     short: true
                },
                {
                     title: 'Built by',
                     value: 'Jenkins',
                     short: true
                }]
            },
            success: options[:success]
        )
    end
end

platform :ios do
    desc "Push a new beta build to TestFlight"

    lane :send_message do
        send_message_to_mattermost({
            :version_number => ENV['VERSION_NUMBER'],
            :build_number => ENV["BUILD_NUMBER"],
            :pretext => ENV['MAIN_APP_IDENTIFIER'],
            :title => 'Unsuccessful Build',
            :thumb_url => 'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/move-to-ios-icon.png',
            :msg => "My message...",
            :default_payloads => [:lane],
            :success => true
        })
    end
    lane :beta do
        increment_build_number(xcodeproj: "linphone.xcodeproj")
        build_app(workspace: "linphone.xcworkspace", scheme: "linphone")
        upload_to_testflight
    end
end
